import { QueryInterface, Op } from 'sequelize';

export async function up({ context }: { context: QueryInterface }) {
  await context.bulkInsert('ui_texts', [
    {
      key_name: 'header_title',
      screen: 'home',
      language: 'en',
      content: 'Chasing the Light of Nature',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'header_title',
      screen: 'home',
      language: 'fin',
      content: 'Luonnonvaloa kuvaamassa',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'welcome_title',
      screen: 'home',
      language: 'en',
      content: 'Welcome!',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'welcome_title',
      screen: 'home',
      language: 'fin',
      content: 'Tervehdys!',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'welcome_name',
      screen: 'home',
      language: 'en',
      content: "I'm Antti Kortelainen,",
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'welcome_name',
      screen: 'home',
      language: 'fin',
      content: 'Olen Antti Kortelainen,',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'welcome_text',
      screen: 'home',
      language: 'en',
      content:
        'A passionate nature photography enthusiast from Leppävirta, Finland.This website is a small window into the world of my passion. Here you’ll find moments I’ve captured through the lens of my camera – a selection of images that I feel are successful, meaningful, and dear to me. Each photo has been born in the heart of nature – sometimes after long waits and quiet observation, other times thanks to quick reactions and happy coincidences. For me, nature photography is a way to slow down, to learn, and perhaps to be part of something greater. The images that matter most to me don’t always come from dramatic landscapes or rare species, but from small, everyday moments that reflect the beauty of the nature close to home. I hope my photos awaken in you the same kind of joy, wonder, and respect for nature that they bring to me. Thanks for stopping by – take your time and dive into the beauty of the nature!',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'welcome_text',
      screen: 'home',
      language: 'fin',
      content:
        'Innokas luontokuvauksen harrastaja Leppävirralta. Tämä sivusto on pieni ikkuna intohimoni maailmaan. Pääset mukaan tarkastelemaan hetkiä, jotka olen saanut vangittua kamerani linssin läpi. Olen koonnut tänne valikoiman kuvia, jotka ovat mielestäni onnistuneita, merkityksellisiä ja mieluisia. Jokainen kuva on syntynyt luonnon helmassa – joskus pitkän odotuksen ja hiljaisen tarkkailun tuloksena, toisinaan taas nopean reaktion ja onnellisen sattuman seurauksena. Luontokuvaus on minulle tapa rauhoittua, oppia ja ehkäpä olla osa jotakin suurempaa. Minulle tärkeimmät kuvat eivät aina synny dramaattisista maisemista tai harvinaisista lajeista, vaan pienistä ja arkisista hetkistä, jotka kertovat jotain olennaista myös oman lähiluontomme kauneudesta. Toivon, että kuvani herättävät myös sinussa samanlaista iloa, ihastusta ja kunnioitusta luontoa kohtaan kuin minussa. Mukava, että piipahdit ja sukella rauhassa mukaan luonnon kauneuteen!',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'gallery_header',
      screen: 'home',
      language: 'en',
      content: 'Photo Gallery',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'gallery_header',
      screen: 'home',
      language: 'fin',
      content: 'Kuvagalleria',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'gallery_text',
      screen: 'home',
      language: 'en',
      content:
        'Through the images below you can access my photo gallery. The images are divided into four categories: birds, mammals, landscapes and nature.',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'gallery_text',
      screen: 'home',
      language: 'fin',
      content:
        'Alla olevien kuvien kautta pääset kuvagalleriaani. Kuvat on jaoteltu neljään kategoriaan: linnut, nisäkkäät, maisemat ja luonto.',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_title_bird',
      screen: 'home',
      language: 'en',
      content: 'Birds',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_title_bird',
      screen: 'home',
      language: 'fin',
      content: 'Linnut',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_title_mammals',
      screen: 'home',
      language: 'en',
      content: 'Mammals',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_title_mammals',
      screen: 'home',
      language: 'fin',
      content: 'Nisäkkäät',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_title_landscapes',
      screen: 'home',
      language: 'en',
      content: 'Landscapes',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_title_landscapes',
      screen: 'home',
      language: 'fin',
      content: 'Maisemat',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_title_nature',
      screen: 'home',
      language: 'en',
      content: 'Nature',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_title_nature',
      screen: 'home',
      language: 'fin',
      content: 'Luonto',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_text_bird',
      screen: 'home',
      language: 'en',
      content:
        'Birds fascinate me in an inexplicable way. They are also especially close to my heart because my deep passion for photography, and particularly nature photography, was ignited by an encounter with a Ural owl.',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_text_bird',
      screen: 'home',
      language: 'fin',
      content:
        'Linnut kiehtovat minua selittämättömällä tavalla. Lisäksi ne ovat erityisesti lähellä sydäntäni, koska palava innostus valokuvaamiseen ja etenkin luontokuvaamiseen sai roihun sytyttäneen kipinän kohtaamisesta viirupöllön kanssa.',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_text_mammals',
      screen: 'home',
      language: 'en',
      content:
        "Photographing mammals, especially large animals, is certainly the most challenging. Not least because they are so rarely seen. Perhaps that's also why just spotting one is always a special experience.",
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_text_mammals',
      screen: 'home',
      language: 'fin',
      content:
        'Nisäkkäiden ja varsinkin isojen eläinten kuvaaminen on varmasti haastavinta. Eikä vähiten siksi, että niitä pääsee näkemään vain niin kovin harvoin. Ehkäpä  myös siksi jo pelkkä eläimen näkeminen on aina erityinen kokemus.',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_text_landscapes',
      screen: 'home',
      language: 'en',
      content:
        'The beauty of landscape photography, in my opinion, is that no matter how many times I visit the same location, the scenery and the photos always change, revealing new and unexpected details each time.',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_text_landscapes',
      screen: 'home',
      language: 'fin',
      content:
        'Maisemakuvaamisen suola on mielestäni se, että vaikka käyn kuinka monesti samalla paikalla kuvaamassa, niin kerta toisensa jälkeen maisema ja kuva muuttuvat ja niistä löytää yllättäen uusia piirteitä.',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_text_nature',
      screen: 'home',
      language: 'en',
      content:
        "Nature is an eternal source of inspiration. I don't consider myself particularly gifted artistically. However, by observing nature, I too can sometimes discover the art it creates. Admiring it is something I can certainly do.",
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'card_text_nature',
      screen: 'home',
      language: 'fin',
      content:
        'Luonto on ikiaikainen inspiraation lähde. Itseäni en pidä erityisen lahjakkaana taiteellisesti. Kuitenkin luontoa tarkkailemalla minäkin toisinaan saatan löytää luonnon luomaa taidetta. Sen ihastelu minulta onnistuu kyllä.',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'title_pom',
      screen: 'home',
      language: 'fin',
      content: 'Kuukauden kuva',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'title_pom',
      screen: 'home',
      language: 'en',
      content: 'Photo of the Month',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'text_pom',
      screen: 'home',
      language: 'en',
      content:
        'Every month, I choose a special photo that has stayed in my mind for one reason or another. It could be a moment I managed to capture at just the right time, a technically challenging shot, or simply an image that evokes emotions and memories. I also want to offer a glimpse into the story behind the photo – where and how it was taken, what made the moment unique, and what thoughts it brings to mind. When relevant, I’ll also share technical details, such as the equipment and settings used, as well as any post-processing steps. My goal is to share not only beautiful and interesting images but also the stories behind them. I hope this section inspires you to see the world around you in a new way – and perhaps even pick up a camera yourself to capture your own special moments!',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      key_name: 'text_pom',
      screen: 'home',
      language: 'fin',
      content:
        'Joka kuukausi valitsen yhden erityisen kuvan, joka on jäänyt mieleenitavalla tai toisella. Se voi olla hetki, jonka onnistuin tallentamaan juuri oikeaan aikaan, teknisesti haastava otos tai yksinkertaisesti kuva, joka herättää tunteita ja muistoja. Haluan myös tarjota kurkistuksen kuvan taustoihin – missä ja miten se on otettu, mikä teki tilanteesta ainutlaatuisen ja mitä ajatuksia kuva minussa herättää. Kerron tarvittaessa myös teknisistä yksityiskohdista, kuten käytetystä kalustosta ja asetuksista, sekä mahdollisista jälkikäsittelyvaiheista. Tavoitteeni on jakaa paitsi kauniita ja mielenkiintoisia kuvia, myös tarinoita niiden takaa. Toivon, että tämä osio inspiroi sinua katsomaan ympäröivää maailmaa uusin silmin – ehkä jopa tarttumaan itse kameraan ja ikuistamaan omia hetkiäsi!',
      role: 'all',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);
}

export async function down({ context }: { context: QueryInterface }) {
  await context.bulkDelete('ui_texts', {
    key_name: {
      [Op.in]: [
        'header_title',
        'welcome_title',
        'welcome_name',
        'welcome_text',
        'card_title_bird',
        'card_title_mammals',
        'card_title_landscapes',
        'card_title_nature',
        'card_text_bird',
        'card_text_mammals',
        'card_text_landscapes',
        'card_text_nature',
        'title_pom',
        'text_pom',
      ],
    },
  });
}
