name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install backend dependencies
        run: cd backend && npm install

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Build project
        run: cd frontend && npm run build

      - name: Copy backend files to server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" ./backend/ chgqkclj@akphotography.fi:public_html/backend/

      - name: Copy frontend files to server
        run: |
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" ./frontend/dist/ chgqkclj@akphotography.fi:public_html/dist/

      - name: Create .env file on server
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no chgqkclj@akphotography.fi "echo '${{ secrets.ENV_FILE }}' > public_html/backend/.env && chmod 600 public_html/backend/.env"

      - name: Restart Node.js app
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no chgqkclj@akphotography.fi "cd public_html/backend && pm2 restart index.js || pm2 start index.js"

      - name: Debug server files
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no chgqkclj@akphotography.fi "ls -l public_html && ls -l public_html/dist && ls -l public_html/backend"

      - name: Cleanup private key
        run: rm -f private_key
