name: Deploy Backend and Frontend to Server

on:
  push:
    branches:
      - main

  pull_request:
    branches-ignore:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install backend dependencies
        run: cd backend && npm install

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Build project backend
        run: cd backend && npm run build

      - name: Build project frontend
        run: cd frontend && npm run build

      - name: Prepare SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          ssh-keyscan akphotography.fi >> ~/.ssh/known_hosts

      - name: Remove old frontend dist folder from server
        run: |
          ssh -i ~/.ssh/private_key chgqkclj@akphotography.fi "rm -rf public_html/dist"

      - name: Copy backend files to server
        run: |
          rsync -avz -e "ssh -i ~/.ssh/private_key" ./backend/buildBackend/ chgqkclj@akphotography.fi:public_html/

      - name: Copy backend node_modules
        run: |
          rsync -avz -e "ssh -i ~/.ssh/private_key" ./backend/node_modules/ chgqkclj@akphotography.fi:public_html/node_modules/

      - name: Copy frontend files to server
        run: |
          rsync -avz -e "ssh -i ~/.ssh/private_key" ./frontend/dist/ chgqkclj@akphotography.fi:public_html/dist/

      - name: Create .env file on server
        run: |
          ssh -i ~/.ssh/private_key chgqkclj@akphotography.fi "echo '${{ secrets.ENV_FILE }}' > public_html/.env && chmod 600 public_html/.env"

      - name: Restart Node.js app
        run: |
          ssh -i ~/.ssh/private_key chgqkclj@akphotography.fi "cd public_html && pm2 restart index.js || pm2 start index.js"

      - name: Debug server files
        run: |
          ssh -i ~/.ssh/private_key chgqkclj@akphotography.fi "ls -l public_html && ls -l public_html/dist"

      - name: Create tag
        id: create_tag
        run: |
          TAG_NAME="v$(date +'%Y.%m.%d.%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          release_name: Release ${{ steps.create_tag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Cleanup SSH key
        run: |
          rm -f ~/.ssh/private_key
